import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id="heading">
          <Image
            height="40"
            width="131"
            alt="spotify logo"
            src="/spotify-logo.svg"
          />
        </div>

        <p>Starting coding the project</p>
      </main>
    </div>
  );
}
